apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: finance
  template:
    metadata:
      labels:
        app: finance
    spec:
      containers:
        - name: finance-app
          image: finance-service:1.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 1Gi
              cpu: "1"